# Site settings
title: Curriculum Vitae
email: byungyoonc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curriculum Vitae page of Choi Byungyoon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://byungyoonc.github.io" # the base hostname & protocol for your site
twitter_username: kevincby_
github_username:  byungyoonc

# Build settings
markdown: kramdown
permalink: pretty